import React, { useState, useEffect } from 'react';
import { X, Mail, ExternalLink, RefreshCw, Clock } from 'lucide-react';
import { fetchNotificationLogs } from '../api';
import { NotificationLog } from '../types';

interface NotificationsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const NotificationsModal: React.FC<NotificationsModalProps> = ({ isOpen, onClose }) => {
  const [logs, setLogs] = useState<NotificationLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedLog, setSelectedLog] = useState<NotificationLog | null>(null);

  const loadLogs = async () => {
    try {
      setLoading(true);
      const data = await fetchNotificationLogs();
      setLogs(data);
      if (data.length > 0 && !selectedLog) {
        setSelectedLog(data[0]);
      }
    } catch {
      // Fallback
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      loadLogs();
    }
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-4xl bg-white rounded-lg shadow-elevated border border-[#E8E1D6] overflow-hidden max-h-[92vh] flex flex-col">
        {/* Header */}
        <div className="p-5 border-b border-[#E8E1D6] flex items-center justify-between bg-[#FAF7F2]">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-white rounded-md border border-[#E8E1D6] text-[#C1440E]">
              <Mail className="w-5 h-5" />
            </div>
            <div>
              <h2 className="font-serif text-xl font-medium text-[#1F1B16]">
                Notification Activity Feed
              </h2>
              <p className="text-[11px] text-[#6B6459]">
                Emails generated by the event-driven Notification Service
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={loadLogs}
              disabled={loading}
              className="btn-secondary px-3 py-1.5 text-xs gap-1.5"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
              <span>Refresh</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-[#6B6459] hover:text-[#1F1B16] rounded-md hover:bg-white"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-hidden flex flex-col md:flex-row">
          {/* Logs List (Left) */}
          <div className="md:w-1/3 border-b md:border-b-0 md:border-r border-[#E8E1D6] overflow-y-auto max-h-[40vh] md:max-h-none">
            {loading ? (
              <div className="p-8 text-center text-xs text-[#6B6459]">Fetching dispatch logs...</div>
            ) : logs.length === 0 ? (
              <div className="p-8 text-center text-xs text-[#6B6459]">
                No transactional emails logged yet. Place an order to see the event pipeline dispatch in real-time!
              </div>
            ) : (
              <div className="divide-y divide-[#E8E1D6]">
                {logs.map((log) => (
                  <div
                    key={log.id}
                    onClick={() => setSelectedLog(log)}
                    className={`p-3.5 cursor-pointer transition-colors text-left ${
                      selectedLog?.id === log.id ? 'bg-[#FAF0EB]' : 'hover:bg-[#FAF7F2]'
                    }`}
                  >
                    <div className="flex items-center justify-between text-[10px] text-[#6B6459]">
                      <span className="font-mono">{log.eventType}</span>
                      <span>
                        {new Date(log.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                    <div className="font-medium text-xs text-[#1F1B16] mt-1 line-clamp-1">{log.subject}</div>
                    <div className="text-[11px] text-[#6B6459] mt-0.5">To: {log.recipientEmail}</div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Email Preview (Right) */}
          <div className="md:w-2/3 p-5 overflow-y-auto bg-[#FAF7F2] flex-1">
            {selectedLog ? (
              <div className="space-y-4">
                <div className="bg-white p-4 rounded-md border border-[#E8E1D6] space-y-2 text-xs">
                  <div className="flex justify-between items-center">
                    <span className="font-medium text-[#1F1B16] text-sm">{selectedLog.subject}</span>
                    {selectedLog.previewUrl && (
                      <a
                        href={selectedLog.previewUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center gap-1 text-[11px] text-[#C1440E] hover:underline font-medium"
                      >
                        <span>Ethereal Preview</span>
                        <ExternalLink className="w-3 h-3" />
                      </a>
                    )}
                  </div>
                  <div className="text-[11px] text-[#6B6459]">
                    Recipient: <strong className="text-[#1F1B16]">{selectedLog.recipientEmail}</strong>
                  </div>
                </div>

                <div
                  className="bg-white p-4 rounded-md border border-[#E8E1D6] shadow-soft overflow-hidden"
                  dangerouslySetInnerHTML={{ __html: selectedLog.htmlContent }}
                />
              </div>
            ) : (
              <div className="h-full flex items-center justify-center text-xs text-[#6B6459]">
                Select an email log on the left to preview message contents
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
